[package]
name = "open-keyprec-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
log = "0.4.17"
midir = "0.9.1"
pretty_env_logger = "0.4.0"
serialport = "4.2.0"
